apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain
  template:
    metadata:
      labels:
        app: brain
        version: v1
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: docker.pkg.github.com/sap-samples/teched2020-developer-keynote/brain:latest
        imagePullPolicy: Always
        name: brain        
        ports:
        - name: http
          containerPort: 4004
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 32Mi
        envFrom:
          - configMapRef:
              name: appconfig
      imagePullSecrets:
      - name: regcred                          

---              
apiVersion: v1
kind: Service
metadata:
  name: brain
  labels:
    app: brain
spec:
  ports:
  - port: 4004
    name: http
    targetPort: 4004
  selector:
    app: brain  


---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: brain
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: brain
    port: 4004
    host: brain
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","PATCH","HEAD"]
      accessStrategies:
        - handler: noop
          config: {}